spring:
  application:
    name: rest-api-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sps-data
      username: admin
      password: admin123
      authentication-database: admin

server:
  port: 8080  # Standard Port für REST API

mqtt:
  broker:
    url: tcp://sr-labor.ddns.net:1883
    username: paul.hartung@stud.hs-bochum.de
    password: "018464155"
    client-id: rest-api-${random.uuid}
  topics:
    wago:
      status: Wago750/Status
      control: Wago750/Control
    siemens:
      ist: S7_1500/Temperatur/Ist
      soll: S7_1500/Temperatur/Soll
      differenz: S7_1500/Temperatur/Differenz
    test: Random/Integer

logging:
  level:
    de.hochschule.bochum: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
  file:
    name: logs/rest-api-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
