spring:
  application:
    name: rest-api-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sps-data
      username: admin
      password: admin123
      authentication-database: admin

server:
  port: 8080  # Standard Port für REST API

mqtt:
  broker:
    url: tcp://sr-labor.ddns.net:1883
    username: paul.hartung@stud.hs-bochum.de
    password: "018464155"
    client-id: rest-api-${random.uuid}
  topics:
    wago:
      control: Wago750/Control

logging:
  level:
    de.hochschule.bochum: DEBUG
